FROM python:3.10.4-buster

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./hello.py /code/hello.py

CMD ["uvicorn", "hello:app", "--host", "0.0.0.0", "--port", "80"]